from typing import Any, Dict, Optional, Tuple

from src.agents.tool_agent import create_general_agent
from src.chains.basic_chain import create_intelligent_chain
from src.services.session_manager import SessionManager


class AIService:
    def __init__(self, session_manager: SessionManager):
        self._session_manager = session_manager
        self._agent = create_general_agent()
        self._chain = create_intelligent_chain()

    def invoke_agent(
        self,
        prompt: str,
        thread_id: str,
        user_id: str,
        image_content: Optional[Dict[str, Any]] = None,
    ) -> Tuple[str, bool]:
        try:
            enriched_prompt = self._inject_memory_context(prompt, user_id)

            if image_content:
                user_payload = [
                    {"type": "text", "text": enriched_prompt},
                    image_content,
                ]
            else:
                user_payload = enriched_prompt

            response = self._agent.invoke(
                {"messages": [("user", user_payload)]},
                config={"configurable": {"thread_id": thread_id}},
            )

            messages = response.get("messages", [])
            if not messages:
                return "No response generated by agent.", True

            content = messages[-1].content
            if isinstance(content, list):
                content = "\n".join(
                    item.get("text", "") for item in content if isinstance(item, dict)
                ).strip()

            self._capture_user_memory(prompt, user_id)

            return str(content), False
        except Exception as exc:
            return f"Agent error: {exc}", True

    def invoke_chain(self, prompt: str, user_id: str) -> Tuple[str, bool]:
        try:
            enriched_prompt = self._inject_memory_context(prompt, user_id)
            response = self._chain.invoke({"input": enriched_prompt})
            self._capture_user_memory(prompt, user_id)
            return str(response), False
        except Exception as exc:
            return f"Chain error: {exc}", True

    def _inject_memory_context(self, prompt: str, user_id: str) -> str:
        memories = self._session_manager.get_user_memories(user_id=user_id, limit=12)
        if not memories:
            return prompt

        lines = "\n".join(f"- {m}" for m in memories)
        return (
            "[Persistent User Memory]\n"
            f"{lines}\n\n"
            "Use these memories when relevant and truthful.\n\n"
            f"[Current User Message]\n{prompt}"
        )

    def _capture_user_memory(self, prompt: str, user_id: str) -> None:
        text = prompt.strip()
        if not text:
            return

        low = text.lower()
        trigger_phrases = [
            "remember",
            "my name is",
            "i am",
            "i work",
            "i like",
            "i prefer",
            "my favorite",
            "call me",
        ]
        if any(p in low for p in trigger_phrases):
            self._session_manager.add_user_memory(user_id=user_id, memory_text=text[:500])
